Implemented createRecordInBackground
Probably need to add an official completedorders table in db.

java.sql.SQLException: Before start of result set 
is being received but data is still written in.